version: '2'
services:
  mtail:
    build: 
      context: ./mtail
    command:
      - "-progs"
      - "/etc/mtail"
      - "-logs"
      - "/var/log/chia/debug.log"
      - "-logtostderr"
    ports:
      - "3903:3903"
    volumes:
      #- ${HOME}/.chia/mainnet/log/debug.log:/var/log/chia/debug.log
      - C:/Users/USERNAME/.chia/mainnet/log/debug.log:/var/log/chia/debug.log
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - "9100:9100"
  prometheus:
    build: 
      context: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - prom_data:/prometheus
  grafana:
    build: 
      context: ./grafana
    ports:
      - "3000:3000"
volumes:
  prom_data:
